### PR TITLE
use const for the raw response length

### PR DESCRIPTION
**Pull request by 9Morello**

### CODE REVIEW

**Comment by farzher** [comment]
i actually recently removed this because i didn't notice any performance difference. the js engine seems to auto cache the length in for loops now. i'm not sure this optimization is relevant anymore

https://github.com/farzher/bunzer/commit/31ba2ac59eae7304534db540ab717945db16b037#diff-4d59bec5ab190071779e69c705bec6edafdf35f1ceed4f4435f2ed562bf4a126L18

**Comment by 9Morello** [comment]
@farzher Wow, that is pretty neat, and it's nice that you already benchmarked that. Thanks for the info, I'm closing the pull request :+1:

**Comment by melroy89** [comment]
What about using `const first_space = raw_http_request.indexOf(' ');` ? instead of those for loops???

**Comment by farzher** [comment]
> What about using `const first_space = raw_http_request.indexOf(' ');` ? instead of those for loops???

i originally wrote it that way https://github.com/farzher/bunzer/commit/adef14c2b2ed6948411242ce3ee2bbec2e1de35f
but changed it because i thought the loop was quicker. but i changed other stuff at the same time.

after retesting it looks like indexOf is quicker... oops. although it's hard to notice any difference i'll probably change all the loops back to indexOf since it's less code anyway!

**Comment by melroy89** [comment]
Yea I think indexof is indeed quicker. Thanks for your fast replies everywhere in your project. Consider using it where possible of course.

**Pull request closed without merging**
